### ISSUE TITLE
Wrong exception message

### ISSUE THREAD

**Issue by marmotz** [hoaproject/Http#27]
In following code, i think the line 546 should be deleted:
https://github.com/hoaproject/Http/blob/6d3e114b48a63cf6b9532f9e9607cebade6314ef/Response/Response.php#L544-L548

**Comment by marmotz** [comment]
My bad... I close this ticket

**Comment by Hywan** [comment]
Why do you think it should be removed?

**Comment by marmotz** [comment]
Because I misunderstood your code and the error message I had.

Sorry to have created a wrong issue.

**Comment by Hywan** [comment]
That's OK :-).
